"""
Purpose: Service to generate a Markdown security report from a ScanResult.

Responsibilities:
- Summarize total findings, critical/high counts.
- List findings grouped by severity.
- Provide remediation advice.

Dependencies:
- app.models.scan_result.ScanResult
- datetime for timestamps

Usage:
    report = ReportService().generate(scan_result)
"""

from datetime import datetime
from typing import List

from app.models.scan_result import ScanResult, Finding


class ReportService:
    """Generates a rich Markdown security report for a ScanResult."""

    def _format_finding(self, f: Finding) -> str:
        return (
            f"- **[{f.severity}]** `{f.file_path}`:{f.line_number or '?'} – {f.title}\n"
            f"  - Description: {f.description or 'N/A'}\n"
            f"  - Recommendation: {f.recommendation or 'N/A'}\n"
        )

    def generate(self, result: ScanResult) -> str:
        """Return a Markdown string summarizing the scan results.

        The report includes:
        * Header with scan ID and timestamp.
        * Summary table.
        * Detailed findings grouped by severity (Critical, High, Medium, Low, Info).
        """
        total = result.total_findings
        critical = result.critical_findings
        high = result.high_findings
        timestamp = result.timestamp.isoformat()

        markdown = []
        markdown.append(f"# SecureGuard Scan Report – {result.scan_id}\n")
        markdown.append(f"**Repository:** {result.repository}\n")
        markdown.append(f"**Commit:** {result.commit_sha}\n")
        markdown.append(f"**Timestamp:** {timestamp}\n")
        markdown.append("---\n")
        markdown.append("## Summary\n")
        markdown.append(
            f"| Metric | Count |\n|---|---|\n"
            f"| Total Findings | {total} |\n"
            f"| Critical | {critical} |\n"
            f"| High | {high} |\n"
        )
        markdown.append("---\n")

        # Group findings by severity for detailed sections
        severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        grouped = {sev: [] for sev in severity_order}
        for f in result.findings:
            sev = f.severity.upper()
            if sev not in grouped:
                sev = "INFO"
            grouped[sev].append(f)

        for sev in severity_order:
            items = grouped[sev]
            if not items:
                continue
            markdown.append(f"## {sev.title()} Findings ({len(items)})\n")
            for finding in items:
                markdown.append(self._format_finding(finding))
            markdown.append("\n")

        markdown.append("---\n")
        markdown.append("*Generated by SecureGuard – your automated secret & SAST scanner.*\n")
        return "\n".join(markdown)
